export enum RichTextTypeEnum {
  TEXT = "text",
  MENTION = "mention",
  EQUATION = "equation",
}
export enum PropertyTypeEnum {
  TITLE = "title",
  RICH_TEXT = "rich_text",
  NUMBER = "number",
  SELECT = "select",
  MULTI_SELECT = "multi_select",
  DATE = "date",
  PEOPLE = "people",
  FILE = "file",
  CHECKBOX = "checkbox",
  URL = "url",
  EMAIL = "email",
  PHONE_NUMBER = "phone_number",
  FORMULA = "formula",
  RELATION = "relation",
  ROLLUP = "rollup",
  CREATED_TIME = "created_time",
  CREATED_BY = "created_by",
  LAST_EDITED_TIME = "last_edited_time",
  LAST_EDITED_BY = "last_edited_by",
}
